      - name: Deploy to Server
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./test-script.php user@your_server_ip:/var/www/html/
          ssh -i ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@your_server_ip "cd /var/www/html && php test-script.php"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
