name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Debug SSH connection
        run: ssh -v -i ~/.ssh/id_rsa kornilov@158.160.137.62 "echo Hello"

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa kornilov@158.160.137.62 "cd /var/www/html && git pull origin main"

