name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 158.160.137.62 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Connect to Server via SSH
        run: ssh -o StrictHostKeyChecking=no kornilov@158.160.137.62 "echo 'SSH connection successful'"
      
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
