name: Deploy to Ubuntu with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 kornilov@158.160.137.62 echo "SSH connection successful"

